### ISSUE TITLE
Unable to execute query - Found interface graphql.schema.DataFetchingEnvironment, but class was expected

### ISSUE THREAD

**Issue by ieugen** [Distelli/graphql-apigen#18]
I wrote a simple project with graphql-apigen and Spring and I'm getting the bellow exception. I have attached some files that might help [1].

[1] https://gist.github.com/ieugen/d820b95b72bf34364fb519c80245c505

````
java.lang.IncompatibleClassChangeError: Found interface graphql.schema.DataFetchingEnvironment, but class was expected

	at com.distelli.graphql.ResolverDataFetcher.get(ResolverDataFetcher.java:41)
	at graphql.execution.ExecutionStrategy.resolveField(ExecutionStrategy.java:66)
	at graphql.execution.SimpleExecutionStrategy.execute(SimpleExecutionStrategy.java:18)
	at graphql.execution.Execution.executeOperation(Execution.java:85)
	at graphql.execution.Execution.execute(Execution.java:44)
	at graphql.GraphQL.execute(GraphQL.java:201)
	at graphql.GraphQL.execute(GraphQL.java:166)
	at graphql.GraphQL.execute(GraphQL.java:158)
	at gr8pi.graphql.core.GraphqlBootstrapTest.bootstrapGraphql(GraphqlBootstrapTest.java:36)
````

**Comment by ieugen** [comment]
Might be related to https://github.com/Distelli/graphql-apigen/issues/16 . I have 2.4 as dependeny.

**Comment by ieugen** [comment]
It is related to #16

**Comment by brimworks** [comment]
Yes, we need to update to support 2.4.
